### ISSUE TITLE
Error in training the model

### ISSUE THREAD

**Issue by shivanisehrawat4** [cma2015/DeepGS#14]
Error in mx.model.train(symbol, ctx, input.shape, output.shape, params$arg.params,
  :
  object 'TRUE...' not found

Hey, I am getting the above error while training the model using "wheat_example" data.
I am using a Windows PC, device_type="cpu", and have installed the package "mxnet".

**Comment by mawenlong2016** [comment]
> Error in mx.model.train(symbol, ctx, input.shape, output.shape, params$arg.params,
> :
> object 'TRUE...' not found
> 
> Hey, I am getting the above error while training the model using "wheat_example" data.
> I am using a Windows PC, device_type="cpu", and have installed the package "mxnet".


Just try adding a parameter verbose = TRUE in the train_deepGSModel function.
The full code:
trainGSmodel <- train_deepGSModel(trainMat = trainMat,trainPheno = trainPheno,
                validMat = validMat,validPheno = validPheno, markerImage = markerImage, 
                cnnFrame = cnnFrame,device_type = "cpu",gpuNum = 1, eval_metric = "mae",
                num_round = 6000,array_batch_size= 30,learning_rate = 0.01,
                momentum = 0.5,wd = 0.00001, randomseeds = 0,initializer_idx = 0.01,
                verbose = TRUE)

**Comment by GitHUB-ZYD** [comment]
very good i love github
