### ISSUE TITLE
Opening script in RStudio after Docker installation

### ISSUE THREAD

**Issue by Adilbous** [cma2015/DeepGS#6]
Hello, 

First of all, thank you for sharing this work :) 
I followed the instructions for Docker installation for Mac OS. 
It all worked fine. But I am new to the use of Docker.

Once I execute the command line : 
docker run -it -v /Users/adil/documents/GitHub/DeepGS:/home/data malab/deepgs_cpu R

R is launched directly in the terminal, which is not very convenient to work properly. Do you know how I can open a R script (in RStudio for example) with the library, after the docker run ? 

Thanks for your help

**Comment by mawenlong2016** [comment]
Thank you for your attention.
Actually, the docker is a virtual working environment, thus, it can't be directly uploaded the pre-installed packages through the local RStudio. But, we are trying to achieve this.
When we complete it on our DeepGS, we will inform you.

Best wishes.

**Comment by Adilbous** [comment]
Thank you for your quick answer. 
I was able to install the package using a local file. It's working fine. 

Thank you for sharing this work.
